version: '3.9'
services:
  fitflow_database:
    image: postgres:17
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
 
  web:
    depends_on:
      - fitflow_database
    container_name: web_fitflow
    hostname: fitflow.localhost
    build: ./
    working_dir: /usr/src/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONBUFFERED=0
      - DJANGO_SETTINGS_MODULE=fitflow.settings
      - DJANGO_LOG_LEVEL=INFO
      - OAUTHLIB_INSECURE_TRANSPORT=False
      - DEBUG=True
    command: python manage.py runserver fitflow.localhost:8000
    env_file:
      - .env
    volumes:
      - ./project:/usr/src/app

volumes:
  postgres_data: